[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "python311Packages.virtualenv"]

[phases.install]
cmds = [
  "python -m venv venv",
  "source venv/bin/activate && pip install -r backend/requirements.txt",
  "chmod +x start.py"
]

[phases.build]
cmds = ["echo 'Build phase complete - using start.py for startup'"]

[start]
cmd = "source venv/bin/activate && python start.py"

