# nixpacks.toml
# Configuration file for Railway deployment using Nixpacks

[start]
cmd = "gunicorn --bind 0.0.0.0:$PORT backend.src.main:app"

[variables]
PYTHONPATH = "/app"
DATA_DIR = "/data"

[phases.setup]
cmds = [
  "mkdir -p /data/uploads",
  "mkdir -p /data/logs", 
  "mkdir -p /data/backups",
  "chmod 755 /data"
]

