[build]
builder = "nixpacks"

[deploy]
startCommand = "cd backend && python -m gunicorn --bind 0.0.0.0:$PORT --workers 1 --timeout 120 src.main:app"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

