[build]
builder = "nixpacks"

[deploy]
startCommand = "cd backend && python src/main.py"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[env]
PORT = "8180"
FLASK_ENV = "production"
PYTHONPATH = "/app/backend/src"

