[build]
builder = "nixpacks"
buildCommand = "cd backend && pip install --no-cache-dir -r requirements.txt"

[deploy]
startCommand = "cd backend && gunicorn --bind 0.0.0.0:$PORT --workers 4 --timeout 120 --keep-alive 2 --max-requests 1000 --max-requests-jitter 100 src.main:app"
healthcheckPath = "/api/health"
healthcheckTimeout = 30
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[env]
DATA_DIR = "/data"
PYTHONPATH = "/app/backend"
ENVIRONMENT = "production"
DEBUG = "false"
FORCE_HTTPS = "true"

