[build]
builder = "nixpacks"

[deploy]
startCommand = "python3 start.py"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[deploy.envs]
PYTHONPATH = "/app:/app/backend"

