[build]
builder = "dockerfile"
buildCommand = "echo Building Biped Platform..."
watchPatterns = ["backend/**", "frontend/**", "Dockerfile", "railway.toml", "start.sh"]

[deploy]
startCommand = "sh start.sh"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[deploy.envs]
# Cache busting environment variables
"X-Build-Timestamp" = "FORCE_REBUILD_20250703_140000"

# Developer authentication variables
DEV_EMAIL = "dev@biped.app"
DEV_ACCESS_KEY = "dev_biped_2025"

# Redirects removed - let Flask handle routing properly
# Root URL should serve the public landing page, not dashboard

