[build]
builder = "nixpacks"

[deploy]
startCommand = ". /opt/venv/bin/activate && cd backend && gunicorn --bind 0.0.0.0:$PORT src.main:app"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

