[build]
builder = "nixpacks"
buildCommand = "cd backend && pip install --no-cache-dir -r requirements.txt"

[deploy]
healthcheckPath = "/api/health"
healthcheckTimeout = 30
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[env]
DATA_DIR = "/data"
PYTHONPATH = "/app/backend"
ENVIRONMENT = "production"
DEBUG = "false"
FORCE_HTTPS = "true"

