[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 60
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[env]
DATA_DIR = "/data"
ENVIRONMENT = "production"
DEBUG = "false"
FORCE_HTTPS = "true"
PYTHONPATH = "/app/backend"
# OpenCV headless configuration
OPENCV_HEADLESS = "true"
# Disable GUI features
DISPLAY = ""

