[build]
builder = "dockerfile"
buildCommand = "echo Building with Dockerfile..."

[deploy]
startCommand = "./start.sh"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 5

[deploy.envs]
# Cache busting environment variables
CACHE_BUST = "FORCE_REBUILD_20250703_150000"
NO_CACHE = "1"

# Headers for cache control
[deploy.headers]
"Cache-Control" = "no-cache, no-store, must-revalidate"
"Pragma" = "no-cache"
"Expires" = "0"
"X-Build-Timestamp" = "FORCE_REBUILD_20250703_150000"

# Developer authentication variables
DEV_EMAIL = "dev@biped.app"
DEV_ACCESS_KEY = "dev_biped_2025"

# Redirects removed - let Flask handle routing properly
# Root URL should serve the public landing page, not dashboard

