name: Quality Checks

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  quality-checks:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt
        
    - name: Run linting
      run: |
        flake8 backend/src/ tests/ --max-line-length=88 --extend-ignore=E203,W503
        
    - name: Run code formatting check
      run: |
        black --check backend/src/ tests/
        isort --check-only backend/src/ tests/
        
    - name: Run tests
      run: |
        python -m pytest tests/ -v --cov=backend/src --cov-report=xml
        
    - name: Run security checks
      run: |
        # Basic security checks
        ! grep -r -i "password.*=" backend/src/ || exit 1
        ! grep -r -i "secret.*=" backend/src/ || exit 1
        
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false

  javascript-quality:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install ESLint
      run: npm install -g eslint
      
    - name: Run JavaScript linting
      run: |
        eslint backend/src/static/*.js --no-eslintrc --config .eslintrc.json || echo "ESLint issues found, but not failing build"